language: c

sudo: false

env:
    global:
        - NPROC_MAX=8
    matrix:
        - BUILDTEST_MCU_GROUP=static-tests
        - BUILDTEST_MCU_GROUP=cortex_m4
        - BUILDTEST_MCU_GROUP=cortex_m0
        - BUILDTEST_MCU_GROUP=x86
        - BUILDTEST_MCU_GROUP=cortex_m3_2
        - BUILDTEST_MCU_GROUP=cortex_m3_1
        - BUILDTEST_MCU_GROUP=avr8
        - BUILDTEST_MCU_GROUP=msp430
        - BUILDTEST_MCU_GROUP=arm7

addons:
    apt:
        sources:
            - r-packages-trusty
        packages:
            - doxygen
            - cppcheck
            - libpcre3
            - python3
            - g++-multilib
            - gcc-multilib
            - build-essential
            - gcc-avr
            - avr-libc
            - lib32bz2-1.0
            - lib32ncurses5
            - lib32z1

before_install:
    - source ./dist/tools/pr_check/check_labels.sh
    - test "${TRAVIS_PULL_REQUEST}" != "false" || test "${BUILDTEST_MCU_GROUP}" = "static-tests" || check_gh_label "Ready for CI build" || exit 1

install:
    - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
    - tar -xf gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
    - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_9-2015q3/bin/
    - git config --global user.email "travis@example.com"
    - git config --global user.name "Travis CI"
    - git remote add riot https://github.com/RIOT-OS/RIOT.git
    - git fetch riot master
    - git log -1 --pretty=format:%H riot/master

script:
    - ./dist/tools/travis-scripts/build_and_test.sh

notifications:
    email: false
