language: c

sudo: false

cache:
    apt: true
    directories:
        - $HOME/.ccache
        - $HOME/gcc-arm-none-eabi-4_9-2015q3
        - $HOME/mspgcc
        - $HOME/avrgcc

addons:
    apt:
        packages: &common_pkgs
            - libpcre3
            - python3
        packages: &static_test_pkgs
            - *common_pkgs
            - doxygen
            - cppcheck
        packages: &arm_pkgs
            - *common_pkgs
            - lib32bz2-1.0
            - lib32ncurses5
            - lib32z1
        packages: &x86_pkgs
            - *common_pkgs
            - g++-multilib
            - gcc-multilib
            - build-essential
        packages: &avr_pkgs
            - *common_pkgs
            - gcc-avr
            - avr-libc

matrix:
    include:
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=static-tests
          addons: {apt: {packages: *static_test_pkgs}}
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=cortex_m4
          addons: {apt: {packages: *arm_pkgs}}
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=cortex_m0
          addons: {apt: {packages: *arm_pkgs}}
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=x86
          addons: {apt: {packages: *x86_pkgs}}
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=cortex_m3_2
          addons: {apt: {packages: *arm_pkgs}}
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=cortex_m3_1
          addons: {apt: {packages: *arm_pkgs}}
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=avr8
          addons: {apt: {packages: *avr_pkgs}}
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=msp430
        - env: NPROC_MAX=8 BUILDTEST_MCU_GROUP=arm7
          addons: {apt: {packages: *arm_pkgs}}

before_install:
    - source ./dist/tools/pr_check/check_labels.sh
    - test "${TRAVIS_PULL_REQUEST}" != "false" || test "${BUILDTEST_MCU_GROUP}" = "static-tests" || check_gh_label "Ready for CI build" || exit 1

install:
    - test -d $HOME/gcc-arm-none-eabi-4_9-2015q3/bin || wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
    - test -d $HOME/gcc-arm-none-eabi-4_9-2015q3/bin || tar -xf gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2 -C $HOME
    - export PATH=$PATH:$HOME/gcc-arm-none-eabi-4_9-2015q3/bin/

    - test -d $HOME/mspgcc/usr/bin || wget http://launchpadlibrarian.net/145176535/gcc-msp430_4.6.3~mspgcc-20120406-5_amd64.deb
    - test -d $HOME/mspgcc/usr/bin || dpkg -x gcc-msp430_4.6.3~mspgcc-20120406-5_amd64.deb $HOME/mspgcc
    - export PATH=$PATH:$HOME/mspgcc/usr/bin/

    - test -d $HOME/avrgcc/usr/bin || wget https://launchpad.net/ubuntu/+source/gcc-avr/1:4.8-2.1/+build/5894754/+files/gcc-avr_4.8-2.1_amd64.deb
    - test -d $HOME/avrgcc/usr/bin || dpkg -x gcc-avr_4.8-2.1_amd64.deb $HOME/avrgcc
    - export PATH=$PATH:$HOME/avrgcc/usr/bin/

    - git config --global user.email "travis@example.com"
    - git config --global user.name "Travis CI"
    - git remote add riot https://github.com/RIOT-OS/RIOT.git
    - git fetch riot master
    - git log -1 --pretty=format:%H riot/master

script:
    - ./dist/tools/travis-scripts/build_and_test.sh

notifications:
    email: false
