ifneq (,$(filter ccn-lite,$(USEPKG)))
  USEMODULE += ccn-lite-utils
  USEMODULE += evtimer
  USEMODULE += random
  USEMODULE += timex
  USEMODULE += tlsf-malloc
ifeq ($(ICNL_DISABLE),1)
  USEPKG += libicnl
endif
endif
