INCLUDES += -I$(RIOTPKG)/ccn-lite -I$(PKGDIRBASE)/ccn-lite/src
INCLUDES += -I$(PKGDIRBASE)/ccn-lite/src/COMPAS/include
INCLUDES += -I$(RIOTBASE)/sys/posix/include

CFLAGS += -DCCNL_RIOT -DUSE_SUITE_COMPAS
