ifneq (,$(filter ccn-lite,$(USEPKG)))
  USEMODULE += ccn-lite-utils
  USEMODULE += evtimer
  USEMODULE += random
  USEMODULE += timex
  USEMODULE += tlsf-malloc
endif
ifneq (,$(filter libicnl_pseudo,$(USEMODULE)))
  USEPKG += libicnl
endif
